name: Java CI with Maven

on: [ push, pull_request ]

jobs:
  push-to-gcloud:
    name: Push Docker image to Google container registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1.9.0
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - uses: docker/setup-buildx-action@v1
      - name: Push to Google container registry
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}:latest